credentials:
  usernames:
    admin:
      email: admindummy@bcg.com
      name: Admin
      password: $2b$12$uFcRUI32XEHM4s.hFs26DOxPndyjReGroYSy9wRtslnPN/hQKI0Eu

cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name

preauthorized:
  emails:
    - admindummy@bcg.com